//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackoutWindow) DeepCopyInto(out *BlackoutWindow) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackoutWindow.
func (in *BlackoutWindow) DeepCopy() *BlackoutWindow {
	if in == nil {
		return nil
	}
	out := new(BlackoutWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyHealthCheck) DeepCopyInto(out *DependencyHealthCheck) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyHealthCheck.
func (in *DependencyHealthCheck) DeepCopy() *DependencyHealthCheck {
	if in == nil {
		return nil
	}
	out := new(DependencyHealthCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForecastSummary) DeepCopyInto(out *ForecastSummary) {
	*out = *in
	if in.EvaluatedAt != nil {
		in, out := &in.EvaluatedAt, &out.EvaluatedAt
		*out = (*in).DeepCopy()
	}
	out.Horizon = in.Horizon
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForecastSummary.
func (in *ForecastSummary) DeepCopy() *ForecastSummary {
	if in == nil {
		return nil
	}
	out := new(ForecastSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnownEvent) DeepCopyInto(out *KnownEvent) {
	*out = *in
	in.Start.DeepCopyInto(&out.Start)
	in.End.DeepCopyInto(&out.End)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnownEvent.
func (in *KnownEvent) DeepCopy() *KnownEvent {
	if in == nil {
		return nil
	}
	out := new(KnownEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedWorkloadIdentity) DeepCopyInto(out *ObservedWorkloadIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedWorkloadIdentity.
func (in *ObservedWorkloadIdentity) DeepCopy() *ObservedWorkloadIdentity {
	if in == nil {
		return nil
	}
	out := new(ObservedWorkloadIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingPolicy) DeepCopyInto(out *PredictiveScalingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingPolicy.
func (in *PredictiveScalingPolicy) DeepCopy() *PredictiveScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveScalingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingPolicyList) DeepCopyInto(out *PredictiveScalingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PredictiveScalingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingPolicyList.
func (in *PredictiveScalingPolicyList) DeepCopy() *PredictiveScalingPolicyList {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PredictiveScalingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingPolicySpec) DeepCopyInto(out *PredictiveScalingPolicySpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.ForecastHorizon = in.ForecastHorizon
	out.Warmup = in.Warmup
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(ScaleStepPolicy)
		**out = **in
	}
	if in.ScaleDown != nil {
		in, out := &in.ScaleDown, &out.ScaleDown
		*out = new(ScaleStepPolicy)
		**out = **in
	}
	out.CooldownWindow = in.CooldownWindow
	if in.BlackoutWindows != nil {
		in, out := &in.BlackoutWindows, &out.BlackoutWindows
		*out = make([]BlackoutWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KnownEvents != nil {
		in, out := &in.KnownEvents, &out.KnownEvents
		*out = make([]KnownEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DependencyHealthChecks != nil {
		in, out := &in.DependencyHealthChecks, &out.DependencyHealthChecks
		*out = make([]DependencyHealthCheck, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingPolicySpec.
func (in *PredictiveScalingPolicySpec) DeepCopy() *PredictiveScalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictiveScalingPolicyStatus) DeepCopyInto(out *PredictiveScalingPolicyStatus) {
	*out = *in
	if in.ObservedWorkload != nil {
		in, out := &in.ObservedWorkload, &out.ObservedWorkload
		*out = new(ObservedWorkloadIdentity)
		**out = **in
	}
	if in.TelemetryReadiness != nil {
		in, out := &in.TelemetryReadiness, &out.TelemetryReadiness
		*out = new(TelemetryReadinessSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.LastForecast != nil {
		in, out := &in.LastForecast, &out.LastForecast
		*out = new(ForecastSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.LastRecommendation != nil {
		in, out := &in.LastRecommendation, &out.LastRecommendation
		*out = new(RecommendationSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.SuppressionReasons != nil {
		in, out := &in.SuppressionReasons, &out.SuppressionReasons
		*out = make([]SuppressionReason, len(*in))
		copy(*out, *in)
	}
	if in.LastReplay != nil {
		in, out := &in.LastReplay, &out.LastReplay
		*out = new(ReplaySummaryDigest)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictiveScalingPolicyStatus.
func (in *PredictiveScalingPolicyStatus) DeepCopy() *PredictiveScalingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PredictiveScalingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecommendationSummary) DeepCopyInto(out *RecommendationSummary) {
	*out = *in
	if in.EvaluatedAt != nil {
		in, out := &in.EvaluatedAt, &out.EvaluatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecommendationSummary.
func (in *RecommendationSummary) DeepCopy() *RecommendationSummary {
	if in == nil {
		return nil
	}
	out := new(RecommendationSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplaySummaryDigest) DeepCopyInto(out *ReplaySummaryDigest) {
	*out = *in
	if in.WindowStart != nil {
		in, out := &in.WindowStart, &out.WindowStart
		*out = (*in).DeepCopy()
	}
	if in.WindowEnd != nil {
		in, out := &in.WindowEnd, &out.WindowEnd
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplaySummaryDigest.
func (in *ReplaySummaryDigest) DeepCopy() *ReplaySummaryDigest {
	if in == nil {
		return nil
	}
	out := new(ReplaySummaryDigest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleStepPolicy) DeepCopyInto(out *ScaleStepPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleStepPolicy.
func (in *ScaleStepPolicy) DeepCopy() *ScaleStepPolicy {
	if in == nil {
		return nil
	}
	out := new(ScaleStepPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalHealth) DeepCopyInto(out *SignalHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalHealth.
func (in *SignalHealth) DeepCopy() *SignalHealth {
	if in == nil {
		return nil
	}
	out := new(SignalHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuppressionReason) DeepCopyInto(out *SuppressionReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuppressionReason.
func (in *SuppressionReason) DeepCopy() *SuppressionReason {
	if in == nil {
		return nil
	}
	out := new(SuppressionReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryReadinessSummary) DeepCopyInto(out *TelemetryReadinessSummary) {
	*out = *in
	if in.CheckedAt != nil {
		in, out := &in.CheckedAt, &out.CheckedAt
		*out = (*in).DeepCopy()
	}
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]SignalHealth, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryReadinessSummary.
func (in *TelemetryReadinessSummary) DeepCopy() *TelemetryReadinessSummary {
	if in == nil {
		return nil
	}
	out := new(TelemetryReadinessSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmupSettings) DeepCopyInto(out *WarmupSettings) {
	*out = *in
	out.EstimatedReadyDuration = in.EstimatedReadyDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmupSettings.
func (in *WarmupSettings) DeepCopy() *WarmupSettings {
	if in == nil {
		return nil
	}
	out := new(WarmupSettings)
	in.DeepCopyInto(out)
	return out
}
